security.basic.enabled: false
server.servlet.context-path: /csm-service
server.port: 80

access_control_allow_origin : '*'

spring.jpa.show-sql : true
spring.jpa.hibernate.ddl-auto : update
spring.jpa.generate-ddl : true
spring.jpa.properties.hibernate.cache.use_second_level_cache : false
spring.jpa.properties.hibernate.cache.use_query_cache : false
spring.jpa.properties.hibernate.cache.use_structured_entries : false
spring.jpa.properties.hibernate.cache.use_minimal_puts : false
spring.jpa.properties.hibernate.cache.generate_statistics : false
spring.jpa.properties.hibernate.cache.provider_configuration : /ehcache.xml
spring.jpa.properties.hibernate.cache.region.factory_class : org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
spring.jpa.properties.javax.persistence.sharedCache.mode : ENABLE_SELECTIVE

spring.datasource.hikari.minimum-idle: 1
spring.datasource.hikari.initialization-fail-timeout: 10
spring.datasource.continue-on-error: false

#In-Memory Database
#spring.h2.console.enabled : true
#spring.datasource.url : jdbc:h2:mem:testdb
#spring.datasource.driverClassName : org.h2.Driver
#spring.datasource.username : sa
#spring.datasource.password : 
#spring.jpa.database-platform : org.hibernate.dialect.H2Dialect

#MySQL Database
#spring.datasource.url : jdbc:mysql://localhost:3306/bank_csm
#spring.datasource.driverClassName : com.mysql.cj.jdbc.Driver
#spring.datasource.username : root
#spring.datasource.password : root
#spring.jpa.database-platform : org.hibernate.dialect.MySQL57InnoDBDialect

#SQL Server Database
spring.datasource.url : jdbc:sqlserver://localhost:1433;databaseName=csm
spring.datasource.driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username : sa
spring.datasource.password : p@ssw0rd
spring.jpa.database-platform : org.hibernate.dialect.SQLServer2012Dialect

#Health Prob
management.endpoint.health.show-details : always
management.endpoints.web.exposure.exclude :  
management.endpoints.jmx.exposure.include : "*"
management.endpoints.jmx.exposure.exclude : 
management.endpoints.web.exposure.include : health,info,prometheus
management.health.probes.enabled : true


---
spring:
  profiles: docker
#spring.datasource.url : jdbc:mysql://host.docker.internal:3306/bank_csm
spring.datasource.url : jdbc:mysql://mysql-0.mysql:3306/bank_csm
spring.datasource.password : 
---
spring:
  profiles: docker-sqlserver
#spring.datasource.url : jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_SCHEMA:csm}
spring.datasource.url : ${DB_URL}
spring.datasource.username : ${DB_USER:sa}
spring.datasource.password : ${DB_PASSWORD:p@ssw0rd}
---