security.basic.enabled: false
server.servlet.context-path: /trn-service
server.port: 82

access_control_allow_origin : '*'

spring.jpa.show-sql : true
spring.jpa.hibernate.ddl-auto : update
spring.jpa.generate-ddl : true
spring.jpa.properties.hibernate.cache.use_second_level_cache : false
spring.jpa.properties.hibernate.cache.use_query_cache : false
spring.jpa.properties.hibernate.cache.use_structured_entries : false
spring.jpa.properties.hibernate.cache.use_minimal_puts : false
spring.jpa.properties.hibernate.cache.generate_statistics : false
spring.jpa.properties.hibernate.cache.provider_configuration : /ehcache.xml
spring.jpa.properties.hibernate.cache.region.factory_class : org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
spring.jpa.properties.javax.persistence.sharedCache.mode : ENABLE_SELECTIVE

#In-Memory Database
#spring.h2.console.enabled : true
#spring.datasource.url : jdbc:h2:mem:testdb
#spring.datasource.driverClassName : org.h2.Driver
#spring.datasource.username : sa
#spring.datasource.password : 
#spring.jpa.database-platform : org.hibernate.dialect.H2Dialect

#MySQL Database
#spring.datasource.url : jdbc:mysql://localhost:3306/bank_transaction?zerodatetimebehavior=Converttonull 
#spring.datasource.driverClassName : com.mysql.cj.jdbc.Driver
#spring.datasource.username : root
#spring.datasource.password : root
#spring.jpa.database-platform : org.hibernate.dialect.MySQL57InnoDBDialect

#SQL Server Database
spring.datasource.url : jdbc:sqlserver://localhost:1433;databaseName=trn
spring.datasource.driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username : sa
spring.datasource.password : p@ssw0rd
spring.jpa.database-platform : org.hibernate.dialect.SQLServer2012Dialect

#Customer Service Management Module (CSM) details
csm.url: http://localhost:81/csm-service
csm.bankbranch.doadjustment: ${csm.url}/bankbranch/v01/doadjustment
csm.customer.doadjustment: ${csm.url}/csm/v01/adjustaccount
csm.customer.byacno: ${csm.url}/csm/v01/byacno
csm.customer.bycif: ${csm.url}/csm/v01/bycif

---
spring:
  profiles: docker
csm.url: http://csm:81/csm-service
#spring.datasource.url : jdbc:mysql://host.docker.internal:3306/bank_transaction?zerodatetimebehavior=Converttonull
spring.datasource.url : jdbc:mysql://mysql-0.mysql:3306/bank_transaction?zerodatetimebehavior=Converttonull
spring.datasource.password : 
---
spring:
  profiles: docker-sqlserver
csm.url: http://${CSM_HOST:csm}:${CSM_PORT:81}/csm-service
spring.datasource.url : jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_SCHEMA:trn}
spring.datasource.username : ${DB_USER:sa}
spring.datasource.password : ${DB_PASSWORD:p@ssw0rd}
---
